### ISSUE TITLE
Error with code when trying to import model in blender

### ISSUE THREAD

**Issue by Jsavga** [bestdani/msfs2blend#11]
Anytime I try to import a msfs model file into blender with this addon I get this error.

![Screenshot (159)](https://user-images.githubusercontent.com/19418984/102157526-a8c7c380-3e4d-11eb-98ed-68b34c56f8be.png)

**Comment by DOJ85** [comment]
Any workaround?
I have the same error, everything is freshly installed

**Comment by AlexandreAero** [comment]
Same here...

**Comment by TotalAviationJmyt** [comment]
same

**Comment by TotalAviationJmyt** [comment]
> Any workaround?
> I have the same error, everything is freshly installed

if you delete blender from %appdata% and fresh install of blender and fresh install of the addon! should work as it did for me!

**Comment by 7799799** [comment]
I tried to remove Blender from %appdata%, then fresh install Blender and fresh install plugins! But it still doesn't work

**Comment by Zordey** [comment]
I am getting the same error on Linux (Fedora 33) Blender 2.91, fresh install.

**Comment by 7799799** [comment]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_msfs_gltf.py", line 330, in execute
    return import_msfs_gltf(context, self.filepath, self.report)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_msfs_gltf.py", line 301, in import_msfs_gltf
    gltf, buffer = load_gltf_file(gltf_file)
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\addons\io_msfs_gltf.py", line 259, in load_gltf_file
    bin_file_name = gltf_file_path.with_name(gltf['buffers']['uri'])
TypeError: list indices must be integers or slices, not str

location: <unknown location>:-1

**Comment by Jannomag** [comment]
Same error for me on Blender 2.82 and 2.91 (Windows 10). Also did a fresh install including removing the directory under %appdata%.

**Comment by Hamiltonoshane** [comment]
Try 2.90 but delete from appdata first before fresh install, it worked for me

**Comment by Jannomag** [comment]
Nope, doesn't work. Tried in on a freshly installed 2.90 - same error.

**Comment by 7799799** [comment]
> 不，不起作用。嘗試使用全新安裝的2.90-同樣的錯誤。

me too

**Comment by WeOkSim** [comment]
For everyone experiencing this problem of complete error at import - try experimental branch - it worked for me, even without compolete reinstalling. 
I removed main plugin completely (via Blender menu)
My blender looks like installed in vanilla location, maybe this is important

**Comment by davidbuckleyni** [comment]
Choose the experimental branch worked for me

**Comment by bestdani** [comment]
Hello, unfortunately I currently have no MSFS subscription anymore due to lack of time for using it and therefore I cannot test it myself, but it seems that the latest blender updates introduced some API changes that lead to incompatibilities, therefore use the experimental branch.

**Comment by bestdani** [comment]
Some information in the MSFS Forums stated that line 259 has to be changed to: `bin_file_name = gltf_file_path.with_name(gltf['buffers'][0]['uri'])` (note the array index 0 that appears there).

Does this mean the file formats have changed? Does this apply to all or just some models? If someone who _was able to test it_ could make a PR (in the experimental branch) I would be happy to accept it.

**Comment by FreddyPalace** [comment]
Hi folks! Does anyone have found a solution? Tried all your suggestions but still doesn't work for me... Getting crazy!

Appreciate your tips!

**Comment by shidarin** [comment]
I can confirm that adding the `[0]` index as you quoted fixes the problem.

**Comment by greensim** [comment]
> Some information in the MSFS Forums stated that line 259 has to be changed to: `bin_file_name = gltf_file_path.with_name(gltf['buffers'][0]['uri'])` (note the array index 0 that appears there).
> 
> Does this mean the file formats have changed? Does this apply to all or just some models? If someone who _was able to test it_ could make a PR (in the master branch, the experimental branch gets the bin file name by assuming it is the same as the glTF file name) I would be happy to accept it.

Which file?
