### ISSUE TITLE
Add LICENSE.md?

### ISSUE THREAD

**Issue by AdenFlorian** [bestdani/msfs2blend#6]
https://opensource.org/licenses/MIT

**Comment by AdenFlorian** [comment]
I would like to use some of the code in a fork of the official gltf importer that I'm working on: https://github.com/AdenFlorian/glTF-Blender-IO-a32nx

**Comment by bestdani** [comment]
There's a GPL license block at the beginning of the (for now) single source code file.

Afaik using MIT or virtually any other license than GPL would not be compatible with blender's GPL license for any kind of addon.

**Comment by VitusW42** [comment]
fyi Khronos is using an Apache 2.0 license for the glTF addon and it ships with Blender. I used the same for the Blender2MSFS toolkit:
http://www.apache.org/licenses/LICENSE-2.0
